#!/usr/bin/env python3
"""Load services.yaml and render .env.platform.generated content."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from urllib.parse import quote

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "PyYAML required for praam-platform scripts. Install: python3 -m pip install pyyaml"
    ) from exc


def load_services(platform_root: Path) -> dict:
    path = platform_root / "services.yaml"
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise SystemExit(f"Invalid services.yaml at {path}")
    return data


def app_key_to_slug(app_key: str) -> str:
    return app_key.replace("_", "-")


def slug_to_app_key(slug: str) -> str:
    return slug.replace("-", "_")


def resolve_app(services: dict, selector: str) -> tuple[str, dict]:
    apps = services.get("apps") or {}
    if selector in apps:
        return selector, apps[selector]
    normalized = slug_to_app_key(selector)
    if normalized in apps:
        return normalized, apps[normalized]
    for key, app in apps.items():
        if app.get("repo") == selector:
            return key, app
    raise SystemExit(f"Unknown app '{selector}' — check services.yaml apps section")


def host_for_runtime(runtime: str, container_host: str) -> str:
    return "127.0.0.1" if runtime == "host" else container_host


def port_for_runtime(runtime: str, service: dict) -> int:
    if runtime == "host":
        return int(service["host_port"])
    return int(service.get("container_port", service["host_port"]))


def database_url(
    *,
    runtime: str,
    platform: dict,
    schema: str,
    driver: str = "postgresql+psycopg",
) -> str:
    pg = platform["postgres"]
    host = host_for_runtime(runtime, pg["container_host"])
    port = port_for_runtime(runtime, pg)
    user = pg.get("user", "praam")
    password = pg.get("password", "praam_dev")
    database = pg["database"]
    options = quote(f"-csearch_path={schema}", safe="")
    return f"{driver}://{user}:{password}@{host}:{port}/{database}?options={options}"


def redis_url(*, runtime: str, platform: dict, db_index: int) -> str:
    redis = platform["redis"]
    host = host_for_runtime(runtime, redis["container_host"])
    port = port_for_runtime(runtime, redis)
    return f"redis://{host}:{port}/{db_index}"


def litellm_base_url(*, runtime: str, platform: dict) -> str:
    llm = platform["litellm"]
    host = host_for_runtime(runtime, llm["container_host"])
    port = port_for_runtime(runtime, llm)
    path = llm.get("path", "/v1").rstrip("/")
    return f"http://{host}:{port}{path}"


def render_env_lines(app_key: str, app: dict, services: dict) -> list[str]:
    platform = services["platform"]
    runtime = app.get("runtime", "docker")
    schema = app.get("schema", "")
    lines = [
        "# Generated by praam-platform — do not edit",
        f"# App: {app_key}  schema: {schema}  runtime: {runtime}",
        "PRAAM_USE_PLATFORM=1",
        f"PRAAM_PLATFORM_VERSION={services.get('version', 1)}",
        f"PRAAM_SCHEMA={schema}",
    ]

    if app.get("api"):
        lines.append(f"API_PORT={app['api']}")
    if app.get("ui"):
        lines.append(f"UI_PORT={app['ui']}")
    for env_name, port_key in (app.get("port_env") or {}).items():
        if app.get(port_key) is not None:
            lines.append(f"{env_name}={app[port_key]}")

    deps = app.get("dependencies") or []
    if "postgres" in deps and schema:
        lines.append(f"DATABASE_URL={database_url(runtime=runtime, platform=platform, schema=schema)}")
        lines.append(
            f"POSTGRES_HOST={host_for_runtime(runtime, platform['postgres']['container_host'])}"
        )
        lines.append(f"POSTGRES_HOST_PORT={platform['postgres']['host_port']}")
        lines.append(f"POSTGRES_DB={platform['postgres']['database']}")

    redis_roles = app.get("redis") or {}
    if "redis" in deps and redis_roles:
        for role, db_index in sorted(redis_roles.items()):
            url = redis_url(runtime=runtime, platform=platform, db_index=int(db_index))
            if role == "cache":
                lines.append(f"REDIS_URL={url}")
            lines.append(f"REDIS_{role.upper()}_URL={url}")
            lines.append(f"REDIS_{role.upper()}_DB={db_index}")
        lines.append(f"REDIS_HOST_PORT={platform['redis']['host_port']}")
        cache_idx = redis_roles.get("cache")
        celery_idx = redis_roles.get("celery")
        if cache_idx is not None:
            lines.append(
                f"CELERY_BROKER_URL={redis_url(runtime=runtime, platform=platform, db_index=int(cache_idx))}"
            )
        if celery_idx is not None:
            lines.append(
                f"CELERY_RESULT_BACKEND={redis_url(runtime=runtime, platform=platform, db_index=int(celery_idx))}"
            )

    if "litellm" in deps:
        base = litellm_base_url(runtime=runtime, platform=platform)
        lines.append(f"LITELLM_BASE_URL={base}")
        lines.append(f"OPENAI_API_BASE={base}")
        models = platform["litellm"].get("models") or {}
        for alias in ("fast", "reasoning", "embedding"):
            if alias in models:
                lines.append(f"PRAAM_LLM_MODEL_{alias.upper()}={alias}")

    return lines


def output_path(platform_root: Path, github_root: Path, app_key: str, app: dict) -> Path:
    repo = app.get("repo") or app_key.replace("_", "-")
    env_dir = app.get("env_dir") or "."
    return github_root / repo / env_dir / ".env.platform.generated"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("Usage: _services.py render <platform_root> <github_root> <app>", file=sys.stderr)
        return 2

    cmd = argv[1]
    platform_root = Path(argv[2]).resolve()
    github_root = Path(argv[3]).resolve()

    if cmd == "list-apps":
        services = load_services(platform_root)
        for key in sorted((services.get("apps") or {}).keys()):
            print(key)
        return 0

    if cmd == "list-wired-apps":
        services = load_services(platform_root)
        for key in sorted((services.get("apps") or {}).keys()):
            app = services["apps"][key]
            if app.get("platform_wired"):
                print(key)
        return 0

    if cmd == "render":
        app_selector = argv[4]
        services = load_services(platform_root)
        app_key, app = resolve_app(services, app_selector)
        lines = render_env_lines(app_key, app, services)
        out = output_path(platform_root, github_root, app_key, app)
        out.parent.mkdir(parents=True, exist_ok=True)
        content = "\n".join(lines) + "\n"
        out.write_text(content, encoding="utf-8")
        print(f"Wrote {out}")
        return 0

    if cmd == "expected-schemas":
        services = load_services(platform_root)
        schemas = sorted(
            {
                app["schema"]
                for app in (services.get("apps") or {}).values()
                if app.get("schema")
            }
        )
        for schema in schemas:
            print(schema)
        return 0

    if cmd == "check-render":
        app_selector = argv[4]
        services = load_services(platform_root)
        app_key, app = resolve_app(services, app_selector)
        path = output_path(platform_root, github_root, app_key, app)
        expected = "\n".join(render_env_lines(app_key, app, services)) + "\n"
        if not path.is_file():
            print(f"MISSING\t{path}")
            return 1
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            print(f"STALE\t{path}")
            return 1
        print(f"OK\t{path}")
        return 0

    if cmd == "render-json":
        app_selector = argv[4]
        services = load_services(platform_root)
        app_key, app = resolve_app(services, app_selector)
        lines = render_env_lines(app_key, app, services)
        print(json.dumps({"lines": lines, "path": str(output_path(platform_root, github_root, app_key, app))}))
        return 0

    print(f"Unknown command: {cmd}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
