-- Platform init only: schemas, grants, pgvector extension.
-- App tables are owned by each product repo (Alembic / init_db).

CREATE EXTENSION IF NOT EXISTS vector;

CREATE SCHEMA IF NOT EXISTS knowledge_studio;
CREATE SCHEMA IF NOT EXISTS findoc;
CREATE SCHEMA IF NOT EXISTS prism;
CREATE SCHEMA IF NOT EXISTS askhr;
CREATE SCHEMA IF NOT EXISTS plan_copilot;
CREATE SCHEMA IF NOT EXISTS pulse;

GRANT ALL ON SCHEMA knowledge_studio TO praam;
GRANT ALL ON SCHEMA findoc TO praam;
GRANT ALL ON SCHEMA prism TO praam;
GRANT ALL ON SCHEMA askhr TO praam;
GRANT ALL ON SCHEMA plan_copilot TO praam;
GRANT ALL ON SCHEMA pulse TO praam;

ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge_studio GRANT ALL ON TABLES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA findoc GRANT ALL ON TABLES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA prism GRANT ALL ON TABLES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA askhr GRANT ALL ON TABLES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA plan_copilot GRANT ALL ON TABLES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA pulse GRANT ALL ON TABLES TO praam;

ALTER DEFAULT PRIVILEGES IN SCHEMA knowledge_studio GRANT ALL ON SEQUENCES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA findoc GRANT ALL ON SEQUENCES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA prism GRANT ALL ON SEQUENCES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA askhr GRANT ALL ON SEQUENCES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA plan_copilot GRANT ALL ON SEQUENCES TO praam;
ALTER DEFAULT PRIVILEGES IN SCHEMA pulse GRANT ALL ON SEQUENCES TO praam;
